appenders:
  fileappender:
    type: dateFile
    filename: logs/downloader.log
    pattern: '-yyyy-MM-dd'
    layout:
      type: pattern
      pattern: '%d %p - %c:%l - %m%n'
  consoleappender:
    type: console
    layout:
      type: pattern
      pattern: '%d %p - %c:%l - %m%n'
categories:
  default:
    appenders:
      - fileappender
      - consoleappender
    level: info
    enableCallStack: true
